#=================================================
# https://github.com/wukongdaily/RunFilesBuilder
# Description: Build RunFiles using GitHub Actions
# Lisence: MIT
# Author: wukongdaily
# Blog: wkdaily.cpolar.cn
#=================================================

name: Make AdGuardHome ipk package

on:
  workflow_dispatch:
    inputs:
      package_version:
        description: '这里是包版本'
        required: false
        default: 'packages-24.10'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: set PACKAGE_VERSION
        run: |
          package_version="${{ github.event.inputs.package_version }}"
          if [ -z "$package_version" ]; then
            package_version="packages-24.10"
          fi
          echo "PACKAGE_VERSION=$package_version" >> $GITHUB_ENV

      - name: Fetch latest release tag from AdGuardHome
        id: fetch_latest_tag
        run: |
          latest_tag=$(curl -s https://api.github.com/repos/AdguardTeam/AdGuardHome/releases/latest | jq -r '.tag_name')
          echo "LATEST_TAG=$latest_tag" >> $GITHUB_ENV
          echo "tag=$latest_tag" >> $GITHUB_OUTPUT

      - name: Download AdGuardHome binary (aarch64 only)
        run: |
          curl -LO "https://github.com/AdguardTeam/AdGuardHome/releases/download/${{ env.LATEST_TAG }}/AdGuardHome_linux_arm64.tar.gz"
          tar -xzf AdGuardHome_linux_arm64.tar.gz

      - name: Download luci-app-adguardhome IPK (aarch64_cortex-a53 only)
        run: |
          mkdir -p output
          curl -L -o output/luci-app-adguardhome-all.ipk \
            "https://github.com/wukongdaily/RunFilesBuilder/releases/download/AdGuardHome_v0.107.55/luci-app-adguardhome-all.ipk"

      - name: Organize files
        run: |
          cp AdGuardHome/AdGuardHome output/
          chmod +x output/AdGuardHome

      - name: Upload ipk + binary to release
        uses: softprops/action-gh-release@v2.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: AdGuardHome_${{ env.LATEST_TAG }}
          name: "AdGuardHome-${{ env.LATEST_TAG }}"
          files: output/*
          token: ${{ secrets.GITHUB_TOKEN }}
