#=================================================
# https://github.com/wukongdaily/RunFilesBuilder
# Description: Build RunFiles using GitHub Actions
# Lisence: MIT
# Author: wukongdaily
# Blog: wkdaily.cpolar.cn
#=================================================
name: Make nikki ipk package

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch latest release tag from nikki
        id: fetch_latest_tag
        run: |
          latest_tag=$(curl -s https://api.github.com/repos/nikkinikki-org/OpenWrt-nikki/releases/latest | jq -r '.tag_name')
          echo "LATEST_TAG=$latest_tag" >> $GITHUB_ENV

      - name: Download latest nikki ipk for aarch64_cortex-a53
        run: |
          curl -LO $(curl -s https://api.github.com/repos/nikkinikki-org/OpenWrt-nikki/releases/latest | grep -oP '"browser_download_url":\s*".*nikki_aarch64_cortex-a53-openwrt-24.10.tar.gz"' | cut -d '"' -f 4)
          tar -xvzf nikki_aarch64_cortex-a53-openwrt-24.10.tar.gz

      - name: Organize ipk files
        run: |
          mkdir -p output
          cp nikki_aarch64_cortex-a53-openwrt-24.10/*.ipk output/ 2>/dev/null || echo "未找到 ipk 文件"

          # 修正文件名中的 ~ 字符
          pushd output >/dev/null || exit 1
          for file in *~*.ipk; do
            [ -e "$file" ] || continue
            new_file="$(echo "$file" | tr -d '~')"
            if [ -e "$new_file" ]; then
              echo "目标文件已存在，跳过: $new_file"
              continue
            fi
            mv "$file" "$new_file"
            echo "已重命名: $file -> $new_file"
          done
          popd >/dev/null

      - name: Clean version for tag
        id: clean_version
        run: |
          version="${{ env.LATEST_TAG }}"
          version=${version#v}
          echo "VERSION_CLEAN=$version" >> $GITHUB_ENV
          echo "cleaned_version=$version" >> $GITHUB_OUTPUT

      - name: Upload ipk files to release
        uses: softprops/action-gh-release@v2.1.0
        with:
          tag_name: "nikki-${{ steps.clean_version.outputs.cleaned_version }}"
          name: "nikki-${{ steps.clean_version.outputs.cleaned_version }}"
          files: output/*.ipk
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
