#=================================================
# https://github.com/wukongdaily/RunFilesBuilder
# Description: Build RunFiles using GitHub Actions
# Lisence: MIT
# Author: wukongdaily
# Blog: wkdaily.cpolar.cn
#=================================================
name: Make OpenClash ipk package

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Create openclash directory
        run: mkdir -p openclash

      - name: Checkout OpenClash package branch
        uses: actions/checkout@v4
        with:
          repository: vernesong/OpenClash
          path: OpenClash
          ref: package

      - name: Copy ipk to output
        run: |
          mkdir -p output
          cp OpenClash/master/*.ipk output/

      - name: Get version info
        id: version
        run: |
          first_line=$(head -n 1 OpenClash/master/version)
          echo "version=$first_line" >> $GITHUB_OUTPUT

      - name: Upload to Release
        uses: softprops/action-gh-release@v2.1.0
        with:
          tag_name: "openclash-${{ steps.version.outputs.version }}"
          name: "openclash-${{ steps.version.outputs.version }}"
          files: output/*.ipk
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
