#=================================================
# https://github.com/wukongdaily/RunFilesBuilder
# Description: Build RunFiles using GitHub Actions
# Lisence: MIT
# Author: wukongdaily
# Blog: wkdaily.cpolar.cn
#=================================================
name: Make iStore ipk package

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  make-run:
    runs-on: ubuntu-22.04

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v3

      - name: 📦 安装依赖
        run: sudo apt-get update && sudo apt-get install -y curl

      - name: 🚀 下载 iStore 的所有 ipk
        run: |
          chmod +x shell/store.sh
          ./shell/store.sh

      - name: 📦 收集 ipk
        id: pack
        run: |
          mkdir -p output
          cp store/*.ipk output/

          STORE_IPK=$(ls output/luci-app-store_*.ipk | head -n 1)
          VERSION=$(basename "$STORE_IPK" | sed -n 's/^luci-app-store_\([^-]*-[^_]*\)_.*$/\1/p')
          if [ -z "$VERSION" ]; then
            echo "❌ 无法提取版本号"
            exit 1
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: 📤 上传到 Release
        uses: softprops/action-gh-release@v2.1.0
        with:
          tag_name: "iStore-${{ steps.pack.outputs.version }}"
          name: "iStore-${{ steps.pack.outputs.version }}"
          body_path: ${{ github.workspace }}/info/store.md
          files: output/*.ipk
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
